### ISSUE TITLE
But I am registered... 

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#1]
Nah, cand sa ma apuc si eu de testat... :tada: 
Sunt inregistrata si validata, if I remember well. However on Sign in, I am redirected to this side alley:

![screen shot 2015-07-17 at 00 09 19](https://cloud.githubusercontent.com/assets/13371295/8735111/0ae85baa-2c17-11e5-9faa-09110717eb93.png)

**Comment by lucianferoiu** [comment]
Did you try to access the Partners list? In which case it'd be normal, since you didn't have access rights..  Btw: I just granted you those rights (can manage partners). 
Otherwise, could you try again? And provide more details of the context? For me it works every time, never had any glitch with this...

**Comment by litebluecheese** [comment]
Am incercat sa ma logez pur si simplu, n-am apucat sa accesez nimic. Acu am mai incercat sa intru o data de pe mobil, dar tot nu merge. Am aceeasi eroare ca si prima data, wrong credentials.
I'm in the car, blocked on Valea Prahovei.

Trimis din Yahoo Mail pe Android

De la:"Lucian Feroiu" notifications@github.com
Data:Vi 17 iul. 2015 la 19:17
Subiect:Re: [youvote4eu] But I am registered... (#1)

Did you try to access the Partners list? In which case it'd be normal, since you didn't have access rights.. Btw: I just granted you those rights (can manage partners). 
Otherwise, could you try again? And provide more details of the context? For me it works every time, never had any glitch with this...

**Comment by lucianferoiu** [comment]
Hmm... Maybe (just maybe) there's something wrong with your credentials?! I mean, is it possible that you mistyped the password when you registered?
We can only know if you run a SHA512 over the text of your password and it matches the one in the error log: 

2015-07-17T17:38:16.824619+00:00 app[web.1]: 17:38:16.824 DEBUG app.base.PlatformController - Partner with email xxxx@yahoo.co.uk has failed to present the proper password (SHA) swu23lF0/wxFec5qUfFf042nQZtARqD1oH+n7Mh23r5O0luWyL9zFmPH3eoSVO0bRH7T8p/rQghR7S+kAdYw7A==

Otherwise I would suggest resetting the password...

Good luck with the traffi jam! And btw: you do realise that these comments are as publicly-visible as the code of the project? :D
