### ISSUE TITLE
In the archival results section can't set the bar to 100% No. :-)

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#17]
They look good on the screen these bars but they are not so easy to use in order to set the exact percentage. I wonder if the 1% bug also comes from here...
![screen shot 2015-08-05 at 14 42 02](https://cloud.githubusercontent.com/assets/13371295/9084914/deb46f78-3b80-11e5-9bf0-fe353312914a.png)

**Comment by lucianferoiu** [comment]
Sidenote: the 1% bug does not come from there - I already fixed and closed that issue

**Comment by lucianferoiu** [comment]
I believe you're unreasonable about this one: the slider **can** be set to 100%...
![screen shot 2015-08-09 at 08 13 39](https://cloud.githubusercontent.com/assets/39299/9153662/d1fe9218-3e6e-11e5-8f9d-c5d6d1cd34a2.png)
Maybe on a trackpad you find it difficult, but with the mouse it's pretty easy...

However it is not really easy to set a precise percentage because there are a 100 snap points but the bar would need to be longer to give you that granularity/precision... Would you suggest a plain text box to enter the figures by hand?

**Comment by litebluecheese** [comment]
I was talking about 100% NO sweetie. I get the "No voting registered" instead. Mea culpa I did not describe the bug thoroughly.
