### ISSUE TITLE
I can still vote after closing voting date on Question 20.07.2015

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#8]
For question 20.07.2015, I have set the closing voting date to 21.07.2015. However I can still vote today on it... and I'm afraid I already did vote in the past (not 100% sure, however). Maybe it's just a bit of chaos due to new deployment. The thing is I do not know is if question should be automatically archived after voting has closed, or archived manually when we have results from legislating bodies. Or there should be a new status? (I do not favour this latter option) A bit of analysis is needed here on the questions workflow, the one you despise so deeply... :P

**Comment by lucianferoiu** [comment]
The voting past closing date is most likely a bug (I didn't bother too much about the closing date so far, it's ignored most of the time; you will find other similar instances etc.)

Archiving a question should also be accompanied by adding a conclusion and any last-minute details. So I'd say a question shouldn't be automatically archived after closing date passed but explicitly...

PS: I do not despise workflows but making things more complicated than necessary (to quote the classics: _why can't things be simple instead of complicated?_)

**Comment by litebluecheese** [comment]
Yes, but...
1. How else can you prevent voting on it?
2. Where does the question go - if not in the published/archived pools? 
I would suggest automatic archival with a flag: "Waiting for official results" The questions can also appear in the archived pool of questions and the interface with exactly this label.

PS. Classic wisdom could also be applied in other domains, not only programming. :P

**Comment by lucianferoiu** [comment]
1. Irrelevant - that's why this is a bug and the fix may involve preventing citizens from voting on it (with a nice message saying "You're too bloody late, mate. Votin's closed, gov'nor, go have a pint")
2. It's in the _published_ pool until it is archived, obviously...

I can archive automatically, sure, but no bloomin' flags, and checks and whatnot - keep the damn thing simple, this is not a nuclear plant.
The problem with this one is: what if someone encodes by mistake a closing date that doesn't make sense(i.e. a date from last century): do I follow blindly the date and never open the question? 
This will also breach access rights: someone who can't archive questions but can edit their details can sneak in a ticking bomb then and there... and now I need to take that into account too - it gets hairy...

**Comment by litebluecheese** [comment]
Ok then. Do it like this. Hopefully there won't be too many of these in the interface, to annoy the voter. From my point of view if I can't vote on them they shouldn't be there anymore...

**Comment by litebluecheese** [comment]
I just noticed that for Archived questions you display a "Voting closed" message. We can't have that in both published and archived questions, cause that will be confusing.

**Comment by lucianferoiu** [comment]
OK, that makes sense.... I will not display anything for the archived questions or I will display "archived question" instead...

**Comment by litebluecheese** [comment]
Shouldnt we display the result of the popular votes as you do in published questions after voting?

**Comment by lucianferoiu** [comment]
You mean the _tally_? **Yes X% / No (100-X)%** ? That'd be a good idea, yes.

**Comment by litebluecheese** [comment]
Yes, the tally. At that moment we can call it result.

**Comment by lucianferoiu** [comment]
Cannot vote anymore on published questions past their closing date ( _most questions in TEST, actually_ :D )

**Comment by litebluecheese** [comment]
ok. the closing date can be modified though i suppose, if the question hasn't been archived yet. i can decide to prolong voting time for a given Q

**Comment by lucianferoiu** [comment]
Indeed - and when implementing issue #5, that possibility will be restricted to only a few trusted partners
