### ISSUE TITLE
Total votes in the votes distribution map does not match total votes displayed for question.

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#9]
I imagine this is because the total number of votes for a question is "fake". However, where are the numbers in the map coming from? Fakes as well? I noticed the value for Romania changed in the map when I did vote, so I guess it works though.

**Comment by lucianferoiu** [comment]
Yeah, for some of the questions (most, actually) the numbers are a bit fake... As I explained, on Heroku we are limited to 10k records so in order to both have some content to play with and keep out of the limit (we're somewhere like 7k records now), not all votes that are faked are recorded properly; for some I purposely allowed for duplicate votes from the same fake _citizens_; for others, I used some generic _citizens_ that do not have a country code - and that'w where you see the discrepancy between the total number and the number per country (hint: if you see a voter bearing the EU flag instead of a national one, that's a doubly-fake citizen :D)

I know this is all somewhat confusing but it was the best trade-off... We'll test the voting consistency more accurately once we clean up the DB and add only a handful of questions with no fake data...

**Comment by litebluecheese** [comment]
My next question was what is with the EU flag? Do we allow votes from citizens without country codes? If we are here, I find this "Citizen from Belgium/Holland/... voted" message very impersonal. It would be nice to see a name there and perhaps a small message - if user wants to add one... I know you're ferociously private and more inclined towards a cold/impersonal/minimalist approach, but most like going public (facebook!) and prefer to see names (even only pseudonyms) instead of Citizen X. Makes it look more real as well.

**Comment by lucianferoiu** [comment]
Country choice is mandatory - the EU flag is just a fallback precaution in case something goes awry; and I used that precisely for the fake citizens..

As for names and messages and such... I don't know, it'd be a bigger change... we can add it but we'll need to be convinced before doing this... In that case we should show all votes on a question, not the latest 10 - just to give anyone's narcissistic tendencies a fair chance..

**Comment by litebluecheese** [comment]
Ok. You can show just the last 10 because Citizen X will see his name on the board and be happy and have the chance to make a printscreen, take a pic if he needs a proof of his vote. I'm thinking of the smartphone vote in front of the screen in Brussels and the satisfaction to see your name there, if only for 10s or so. ;-)

**Comment by litebluecheese** [comment]
Btw, the name/message to MEPs idea was also on my mockup screens. But you found it degrading/menacing I guess. :-) However, you know you're not statistically representative. :D

**Comment by lucianferoiu** [comment]
Alright... optional name/nickname/whatever along with country/email details - that we can do.

But a message for each question (click Yes/No -> a popup asking for a message shows up -> type a message and click Send or whatever) will be a bit disruptive... to the voting flow and we might get less votes because of it. We should really think this through...

However, the larger issue here with both (but mostly the latter) is that we open a door to abuse: some pranksters could use famous names and foul language just for the laughs... more so it there's a chance of public fame. Therefore we might risk more with one of these mishaps than with all the gains for engagement of decent citizens...

**Comment by litebluecheese** [comment]
It happens a lot less than you think... I've taken the idea from Avaaz petitioning tool and it is rather impressive to see the names with messages going down the screen - I'm usually reading them and they're not pranksters at all... Some messages are even really nice. I'm the type that also reads comments to news articles and such to see what the commoners have to say :-) We can still think about it though.

**Comment by lucianferoiu** [comment]
I should make a screenshot of your comment for future reference :)

**Comment by litebluecheese** [comment]
We'll find it back... :-)

**Comment by lucianferoiu** [comment]
The initial bug report refers to a side effect of the fake data in _TEST_. Therefore we won't fix anything here. However the discussion/comments revealed a different issue, for which #11 was created instead.
